services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb_data:/data/db
      - ./volumes/configdb:/data/configdb
    entrypoint: ['/usr/bin/mongod', '--bind_ip', '0.0.0.0'] # 接続可能なIPアドレスを指定